language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - doxygen
before_install:
  - sudo apt-get install pccts -y
  - mkdir clutils
  - cd clutils
  - wget http://nturley-buildartifacts.s3-website-us-west-1.amazonaws.com/clutils.tar.gz
  - tar -xvzf clutils.tar.gz
  - sudo cp -vr export/* /usr/local
  - sudo ln -s /usr/local/include/clutils-0.0 /usr/local/include/clutils
  - cd ..
  - echo $LD_LIBRARY_PATH
  - LD_LIBRARY_PATH=/usr/local/lib
  - export LD_LIBRARY_PATH
  # abra
  - aclocal
  # kadabra
  - autoconf
  # ala
  - libtoolize
  # kazam!
  - automake --add-missing
script: ./configure --with-clutils=/usr/local && make
before_deploy:
- make doc
- sudo make install
