language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - dh-autoreconf
      - doxygen
before_install:
  - sudo apt-get install pccts -y
  - mkdir clutils
  - cd clutils
  - wget http://nturley-buildartifacts.s3-website-us-west-1.amazonaws.com/clutils.tar.gz
  - tar -xvzf clutils.tar.gz
  - sudo cp -vr export/* /usr/local
  - dh_autoreconf
